# ================================================= #
#                                                   #
# Thanks to https://github.com/gammazero/workerpool #
#                                                   #
# ================================================= #
language: go

go:
  - 1.13.x
  - 1.14.x
  - tip

before_script:
  - go vet ./...

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)