name: CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - name: Setup Go
      with:
        go-version: '1.15.2'
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: Run build
      run: |
        go build . 
    - name: Run vet & lint
      run: |
        go vet .
        golint .
    - name: Run tests
      run: |
        ./.github/workflows/test.sh
    - name: Run coverage
      run: |
        bash <(curl -s https://codecov.io/bash)
