name: Build
on: [push]
jobs:
  build:
    name: workerpoolxt
    runs-on: ubuntu-latest
    steps:
    - name: Go tip
      uses: actions/setup-go@v2.1.3
      with:
        go-version: tip
      id: "1"
    - name: Build
      run: go build -v .
    - name: Test
      run: ./test.sh
    - name: Install goveralls
      run: go get github.com/mattn/goveralls
    - name: Install gotest
      run: go get -u github.com/rakyll/gotest
    - name: Coveralls
      run: $GOPATH/bin/goveralls -coverprofile=coverage.out -service=github -repotoken=$COVERALLS_TOKEN
